---
- name: Exercice Handlers - Configuration de Nginx sur Ubuntu
  hosts: node
  become: yes
  vars: 
    nginx_listen_port: 80
    nginx_server_message: "Hello from Ansible templated handler!"  

  tasks:
    - name: Installer Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Créer un fichier de configuration personnalisé
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: Redémarrer Nginx

    - name: Démarrer Nginx
      ansible.builtin.service:
        name: nginx
        state: started

  handlers:
    - name: Redémarrer Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
